### ISSUE TITLE
technicolor DGA ( DGA4132 )

### ISSUE THREAD

**Issue by bycippy** [shaiu/technicolor#17]
once the component is installed by HACS, no device is detected. 

are there any other steps to perform to configure it corectly ?

**Comment by shaiu** [comment]
@bycippy  can you try again and check for errors in the logs?

**Comment by R-F-HansenSmith** [comment]
I have the same issue and get the following error:

```shell
Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:356
integration: Device Tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 15:54:24 (1 occurrences)
Last logged: 15:54:24

Error while setting up technicolor platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/technicolor/device_tracker.py", line 47, in async_setup_entry
    router = hass.data[DOMAIN][entry.entry_id][DOMAIN]
             ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: {{This is just some key, not sure if it's secret or not}}
```

**Update:** I've had this integration installed for about a week and have tried everything to get it working - then, after a unrelated home assistant restart, it just started working.

**Comment by RasmusFangel** [comment]
I've had this integration installed for about a week and have tried everything to get it working - then, after a unrelated home assistant restart, it just started working.

**Comment by iz8azz** [comment]
Hi , DGA4132 also here , this is the error in my logs. I'm not able to integrate the DGA4132.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/technicolor/__init__.py", line 48, in async_setup_entry
    hass.async_create_task(hass.config_entries.async_forward_entry_setup(entry, "device_tracker"))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?`


Best Regards


edit : Ok not an issue, edited file __ init__.py as per
[Deprecation warning HASS 2025.1: async_forward_entry_setup during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done](https://github.com/shaiu/technicolor/issues/18)

now is working fine, sorry for it.
